### ISSUE TITLE
Generalize MAS Action Group capabilities

### ISSUE THREAD

**Issue by MOARdV** [MOARdV/AvionicsSystems#227]
Right now, MAS AG can work with any PartModule, provided a) the part or parts it's expected on are listed, and b) the method MAS calls takes 0 parameters.  There are several axes where it could generalized to support just about any mod's interface (or, for that matter, stock KSP modules):

- [ ] Don't require specific part lists.  Scan all parts for the PartModule of interest.
- [ ] Support VesselModule (and, maybe, general-purpose MonoBehaviour).
- [ ] Support limited parameters - only C# PODT (no enums, no Vessel or Part or whatever).  I may be able to support Vessel, provided it's the current vessel that needs to be sent.

One issue this may cause - overlapping AG numbers.  It's going to be a problem if two people define the same extended AG number to different actions.  I may end up having to support named action groups.

**Comment by theonegalen** [comment]
If I'm reading this right, this would be a more generalized solution to the problem of, for example, science controls?

**Comment by MOARdV** [comment]
> If I'm reading this right, this would be a more generalized solution to the problem of, for example, science controls?

I think it would be okay for science controls as a stop-gap.  Incorporating science natively to MAS is the right long-term solution.  All it takes is me wrapping my head around what tasks and queries the MAS interface needs.  Maybe what I should do is start off small and try to tackle one thing at a time with it.

**Comment by theonegalen** [comment]
That sounds good. A simple "Run (All?) Science" and "Transmit (All?) Science" function would probably be good to start with.

**Comment by snakeru** [comment]
Other science-related props that I have are: `ScienceCollect` to send everything to a container and `ScienceReset` to reset everything that didn't fit into a container.

However the last `ScienceReset` has a problem that prevents me from using it: it resets everything, including Goo and MaterialsBay - there is additional logic required to find out if an experiment could be resetted.

**Comment by MOARdV** [comment]
I think I need to add another generalization so that a script can be run, and I need to add an optional query for `fc.GetActionGroup`.  As far as maximum action group id - it's a 32 bit signed integer, so the maximum value is over 2000000000.  There's plenty of room to avoid collisions.  But I will clarify the documentation.

**Comment by MOARdV** [comment]
I think the best approach will be to scrap the current MAS_ACTION_GROUP configuration and start fresh.

```
MAS_ACTION_GROUP
{
  name = MyFancyActionGroup
  ACTION
  {
    ... // see below
  }
  ...
}
```
* **name** - Required.  Name of the action group.  This name is used instead of an action group id for the action group functions.
* **ACTION** - Optional, 0 or more (but if you use 0, this action group does nothing).

For each action:
```
ACTION
{
  name = my action name
  part = a_part; another_part
  module = ModuleLight
  onAction = LightsOn()
  offAction = LightsOff()
  toggleAction =
  getAction = 
}
```
* **name** Optional.  Used for error messages.
* **part** Optional.  When used, only the parts listed will be searched for modules.  If `part` is omitted, *all* parts with the selected module are included.
* **module** Required.  The PartModule that will be used.

**TODO:** finish this documentation.

**Comment by MOARdV** [comment]
Originally, I was thinking this would replace the existing system.  However, I think what I'll do instead is leave the current system intact, get this working, and then deprecate the old system.

**Comment by MOARdV** [comment]
...Or, do I interface with Action Groups Extended (assuming the mod is still around - if not, can I integrate it?).  If I do, I will want to see if there's a way for MAS to edit the extended action groups from the editor.  That's one of the features of the MAS AG - pre-defining the action groups, so specific props are tied to specific actions.

**Comment by MOARdV** [comment]
It looks like AGE is part of the LGG umbrella, with the additional hard dependency mods that that entails.  It's also a GPL3 mod, so I can't incorporate it directly.  I suppose I could subset the behavior as a second DLL in MAS that's GPL, or I can see if I can get the gist of the mod's functionality and implement it myself (which is almost back to square 1)
